CONFIG_ZMK_USB=y
CONFIG_NFCT_PINS_AS_GPIOS=y

CONFIG_ZMK_KEYBOARD_NAME="MB9i"

# ZMK Studio Support
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_RPC=y

# LED de prueba (P0.17) - encendido en verde fijo al iniciar
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=120
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=100
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0
